# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\dgexi\another1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(671, 284)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"background-color: rgb(82, 196, 198);\n"
"color:rgb(255, 117, 75);\n"
"border-radius:10px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(80, 170, 451, 23))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"text-align:center;\n"
"color:rgb(232, 255, 16);\n"
"background-color: rgb(255, 56, 17);\n"
"border-style:none;\n"
"border-radius:10px;\n"
"}\n"
"QProgressBar::chunk{\n"
"border-radius:10px;\n"
"background-color:qlineargradient(spread:pad, x1:0.642, y1:0.766409, x2:0.358, y2:0.414136, stop:0 rgba(131, 183, 255, 237), stop:1 rgba(255, 255, 255, 255))\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 90, 421, 61))
        self.label.setStyleSheet("QLabel{\n"
"font-size:20px;\n"
"}")
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(140, 100, 161, 41))
        self.label_2.setStyleSheet("QLabel{\n"
"font-size:20px;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Downloading:"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
